# docker-compose --file ./docs/docker-compose.yml up --build --force-recreate preview
version: '3.3'
services:
  preview:
    image: netfoundry/mop-api-docs
    build:
      context: .
    volumes:
      - .:/site
    ports:
      - 4000:4000
    environment:
      - JEKYLL_GITHUB_TOKEN
  build:
    image: netfoundry/mop-api-docs
    build:
      context: .
    volumes:
      - ..:/site
    command: sh
    