name: Update Algolia

on:
  push:
    branches:
      - master
      
jobs:
  update-algolia:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Actually Update Algolia
      run: |
        gem install bundler
        gem install jekyll
        bundle exec jekyll algolia --source ./docs --destination ./docs/_site --config ./docs/_config.yml
