name: Update Algolia

on:
  push:
    branches:
      - master
      
jobs:
  update-algolia:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Actually Update Algolia
      env: 
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec jekyll algolia --config ./docs/_config.yml --source ./docs --destination ./docs/_site 
