name: Update Algolia

on:
  push:
    branches:
      - master
      
jobs:
  update-algolia:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Actually Update Algolia
      run: |
        gem install bundler
        gem install jekyll
        bundle exec jekyll algolia --source ./docs --destination ./docs/_site --config ./docs/_config.yml
